name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup go application
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: build application
      run: go build -v ./...

    - name: run tests
      run: go test -v ./...
